RBW_MINIMAL="\
\[$RBW_R_BLUE\]\357\201\224\
\[$RBW_L_BLUE\]\357\201\224\
\[$RBW_R_CYAN\]\357\201\224\
\[$RBW_RESET_ALL\] "

RBW_SIMPLE=" \
\[$RBW_BR_RED\]\357\204\270  \
\[$RBW_BR_CYAN\]\W:\
\[$RBW_RESET_ALL\] "

RBW_HACKER="\
\[$RBW_BR_GREEN\]\u@\h\
\$\
\[$RBW_RESET_ALL\] "

RBW_REGULAR="\
\[$RBW_BR_GREEN\]\u@\h\
\[$RBW_RESET_ALL\]:\
\[$RBW_BR_BLUE\]\W\
\[$RBW_BR_WHITE\]\$\
\[$RBW_RESET_ALL\] "

RBW_ARROW="\
\[$RBW_R_BLACK_ON_WHITE\]\t\[$RBW_R_WHITE_ON_BLACK\]\[$PL_RIGHT_SEPARATOR\]\
\[$RBW_BR_YELLOW_ON_BLACK\] \u@\h\[$RBW_R_BLACK_ON_BLUE\]\[$PL_RIGHT_SEPARATOR\]\
\[$RBW_BR_WHITE_ON_BLUE\] \W\[$RBW_RESET_ALL\]\[$RBW_R_BLUE\]\[$PL_RIGHT_SEPARATOR\]\
\[$RBW_RESET_ALL\] "