RBW_THEME_ARROW="\
\[$RBW_R_BLACK_ON_WHITE\]\t\[$RBW_R_WHITE_ON_BLACK\]\[$PL_RIGHT_SEPARATOR\]\
\[$RBW_BR_YELLOW_ON_BLACK\] \u@\h\[$RBW_R_BLACK_ON_BLUE\]\[$PL_RIGHT_SEPARATOR\]\
\[$RBW_BR_WHITE_ON_BLUE\] \W\[$RBW_RESET_ALL\]\[$RBW_R_BLUE\]\[$PL_RIGHT_SEPARATOR\]\
\[$RBW_RESET_ALL\] "